name: Deploy-test

on:
  push:
    branches:
      - prod

jobs:
  deploy-frontend:
    uses: dev-hub-ai/SuiHubAI/.github/workflows/reusable_deploy_to_ecs.yaml@reusable-workflows/v1
    with:
      ENVIRONMENT: test
      SERVICE_TYPE: sui-fe
      APP_NAME: ai-office
      LAUNCH_TYPE: FARGATE
      DOCKERFILE_PATH: ./frontend/Dockerfile
      DOCKER_CONTEXT: ./frontend
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.TEST_AWS_REGION }}
      ARN_EXECUTION_ROLE: ${{ secrets.TEST_ARN_EXECUTION_ROLE }}
      SECRET_ARN: ${{ secrets.TEST_SECRET_ARN }}
      ECS_CLUSTER_NAME: ${{ secrets.TEST_ECS_CLUSTER_NAME }}
      DOCKER_BUILD_ENVS: |
        ENV VITE_API_URL=${{ secrets.TEST_VITE_API_URL }}
        ENV VITE_APP_NAME='AI Office'
